services:
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./docker/nginx/share/tester:/usr/share/nginx/tester
      - ./docker/nginx/share/tester:/usr/share/nginx/tester
      - nginx-log-volume:/var/log/nginx
    command: [nginx-debug, "-g", "daemon off;"]
  tester:
    build:
      dockerfile: ./docker/services/tester/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - APP_NGINX_ERROR_LOG=/var/log/nginx/error_debug.log
      - APP_NGINX_PORT_ON_HOST=8081
      - APP_WEB_PATH=/app/web
    volumes:
      - ./docker/nginx/share/tester:/app/web
      - nginx-log-volume:/var/log/nginx

volumes:
  # shared-volume:
  nginx-log-volume:
